.TH "TRotativePointer" "3" "February 2020" "hmi" ""

.SH NAME
TRotativePointer \- pointer rotating around the point CP by changing the value of Angle

.SH Description
pointer rotating around the point CP by changing the value of Angle

.SH METHODS
.TP
.B Rotate
.TP
.B Shift
.TP
.B Zoom

.SH Property overview
.TP
.BI Angle  rw
.TP
.BI Center  rw
.TP
.BI Offset  rw
.TP
.BI Radius  rw
