.TH "DrawnControl" "3" "February 2020" "hmi" ""

.SH NAME
DrawnControl \- Types

.SH TYPES
.SS TDrawingClass
TDrawingClass = Class of TDrawing
.br
The class method #HMI.drawncontrol.TDrawnControl.GetDrawingClass uses this to say, for which drawing class the control is made. 

.SH See also
drawncontrol (3),
drawncontrol.types (3)
