.TH "TRectangle" "3" "February 2020" "hmi" ""

.SH NAME
TRectangle \- TElement descendant to add a rectangle to a drawing

.SH Description
TElement descendant to add a rectangle to a drawing

.SH METHODS
.TP
.B Draw
.TP
.B Rotate
.TP
.B Shift
.TP
.B Zoom

.SH Property overview
.TP
.BI Height  rw
.TP
.BI Left  rw
.TP
.BI Top  rw
.TP
.BI Width  rw
