.TH "TLine" "3" "February 2020" "hmi" ""

.SH NAME
TLine \- straight line that starts at SP and ends at EP

.SH Description
straight line that starts at SP and ends at EP

.SH METHODS
.TP
.B Shift
.TP
.B Rotate
.TP
.B Zoom
.TP
.B Draw

.SH Property overview
.TP
.BI Angle  rw
.TP
.BI EP  rw
.TP
.BI Length  rw
.TP
.BI SP  rw
