.TH "TDrawnControl" "3" "February 2020" "hmi" ""

.SH NAME
TDrawnControl \- control, that displays a drawn graphic on its surface

.SH Description
control, that displays a drawn graphic on its surface

.SH METHODS
.TP
.B GetDrawing
.TP
.B GetDrawingClass
.TP
.B Paint
.TP
.B Resize
.TP
.B SetParent

.SH Property overview
.TP
.BI Drawing  r
