.TH "RetroClock" "3" "February 2020" "hmi" ""

.SH NAME
RetroClock \- 

.SH USED UNITS
.TP
.B System
.TP
.B Classes
.TP
.B SysUtils
.TP
.B LResources
.TP
.B Forms
.TP
.B Controls
.TP
.B Graphics
.TP
.B Dialogs
.TP
.B DrawnControl
declaring a TGraphicControl descendant with a Drawing on its Canvas

.SH CLASSES
.TP
.B TClock
.TP
.B TClockScale
.TP
.B TClockScaleLines
.TP
.B TRetroClock

.SH PROCEDURES AND FUNCTIONS
.TP
.B Register

.SH SEE ALSO
retroclock (3),
retroclock.types (3)
